"""drop chunk tables

Revision ID: 5d8a9f6b7c0e
Revises: 2a3b4c5d6e7f
Create Date: 2024-04-01 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8a9f6b7c0e'
down_revision: Union[str, None] = '2a3b4c5d6e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sec_filing_section_chunks')
    op.drop_table('sec_filing_sections')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sec_filing_sections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filing_accession_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('section_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('original_header', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('section_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('char_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['filing_accession_number'], ['sec_filings.accession_number'], name='sec_filing_sections_filing_accession_number_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sec_filing_sections_pkey')
    )
    op.create_table('sec_filing_section_chunks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filing_accession_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('section_db_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ticker', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('form_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('filing_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('section_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subsection_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chunk_order_in_section', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chunk_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('char_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_table', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_footnote', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['filing_accession_number'], ['sec_filings.accession_number'], name='sec_filing_section_chunks_filing_accession_number_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_db_id'], ['sec_filing_sections.id'], name='sec_filing_section_chunks_section_db_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sec_filing_section_chunks_pkey')
    )
    # ### end Alembic commands ### 