"""Create financial tables

Revision ID: e13b299f59c1
Revises: 
Create Date: 2025-05-01 23:42:09.293519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e13b299f59c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('cash_and_equivalents', sa.Float(), nullable=True),
    sa.Column('short_term_investments', sa.Float(), nullable=True),
    sa.Column('cash_and_short_term_investments', sa.Float(), nullable=True),
    sa.Column('accounts_receivable', sa.Float(), nullable=True),
    sa.Column('inventory', sa.Float(), nullable=True),
    sa.Column('total_current_assets', sa.Float(), nullable=True),
    sa.Column('property_plant_equipment', sa.Float(), nullable=True),
    sa.Column('goodwill', sa.Float(), nullable=True),
    sa.Column('intangible_assets', sa.Float(), nullable=True),
    sa.Column('total_non_current_assets', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('accounts_payable', sa.Float(), nullable=True),
    sa.Column('short_term_debt', sa.Float(), nullable=True),
    sa.Column('total_current_liabilities', sa.Float(), nullable=True),
    sa.Column('long_term_debt', sa.Float(), nullable=True),
    sa.Column('total_non_current_liabilities', sa.Float(), nullable=True),
    sa.Column('total_liabilities', sa.Float(), nullable=True),
    sa.Column('common_stock', sa.Float(), nullable=True),
    sa.Column('retained_earnings', sa.Float(), nullable=True),
    sa.Column('total_stockholders_equity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_balance_ticker_date_period', 'balance_sheets', ['ticker', 'date', 'period'], unique=True)
    op.create_index(op.f('ix_balance_sheets_id'), 'balance_sheets', ['id'], unique=False)
    op.create_index(op.f('ix_balance_sheets_ticker'), 'balance_sheets', ['ticker'], unique=False)
    op.create_table('cash_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('depreciation_amortization', sa.Float(), nullable=True),
    sa.Column('changes_in_working_capital', sa.Float(), nullable=True),
    sa.Column('net_cash_from_operating', sa.Float(), nullable=True),
    sa.Column('capital_expenditure', sa.Float(), nullable=True),
    sa.Column('acquisitions', sa.Float(), nullable=True),
    sa.Column('purchases_of_investments', sa.Float(), nullable=True),
    sa.Column('sales_of_investments', sa.Float(), nullable=True),
    sa.Column('net_cash_from_investing', sa.Float(), nullable=True),
    sa.Column('debt_issuance', sa.Float(), nullable=True),
    sa.Column('debt_repayment', sa.Float(), nullable=True),
    sa.Column('share_issuance', sa.Float(), nullable=True),
    sa.Column('share_repurchase', sa.Float(), nullable=True),
    sa.Column('dividends_paid', sa.Float(), nullable=True),
    sa.Column('net_cash_from_financing', sa.Float(), nullable=True),
    sa.Column('net_change_in_cash', sa.Float(), nullable=True),
    sa.Column('cash_at_beginning', sa.Float(), nullable=True),
    sa.Column('cash_at_end', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cashflow_ticker_date_period', 'cash_flows', ['ticker', 'date', 'period'], unique=True)
    op.create_index(op.f('ix_cash_flows_id'), 'cash_flows', ['id'], unique=False)
    op.create_index(op.f('ix_cash_flows_ticker'), 'cash_flows', ['ticker'], unique=False)
    op.create_table('income_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('cost_of_revenue', sa.Float(), nullable=True),
    sa.Column('gross_profit', sa.Float(), nullable=True),
    sa.Column('rd_expenses', sa.Float(), nullable=True),
    sa.Column('sga_expenses', sa.Float(), nullable=True),
    sa.Column('operating_expenses', sa.Float(), nullable=True),
    sa.Column('operating_income', sa.Float(), nullable=True),
    sa.Column('interest_expense', sa.Float(), nullable=True),
    sa.Column('ebt', sa.Float(), nullable=True),
    sa.Column('income_tax', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_income_ticker_date_period', 'income_statements', ['ticker', 'date', 'period'], unique=True)
    op.create_index(op.f('ix_income_statements_id'), 'income_statements', ['id'], unique=False)
    op.create_index(op.f('ix_income_statements_ticker'), 'income_statements', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_income_statements_ticker'), table_name='income_statements')
    op.drop_index(op.f('ix_income_statements_id'), table_name='income_statements')
    op.drop_index('idx_income_ticker_date_period', table_name='income_statements')
    op.drop_table('income_statements')
    op.drop_index(op.f('ix_cash_flows_ticker'), table_name='cash_flows')
    op.drop_index(op.f('ix_cash_flows_id'), table_name='cash_flows')
    op.drop_index('idx_cashflow_ticker_date_period', table_name='cash_flows')
    op.drop_table('cash_flows')
    op.drop_index(op.f('ix_balance_sheets_ticker'), table_name='balance_sheets')
    op.drop_index(op.f('ix_balance_sheets_id'), table_name='balance_sheets')
    op.drop_index('idx_balance_ticker_date_period', table_name='balance_sheets')
    op.drop_table('balance_sheets')
    # ### end Alembic commands ### 